// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFriend = "friend"

// Friend mapped from table <friend>
type Friend struct {
	OwnerID    string    `gorm:"column:owner_id;primaryKey" json:"owner_id"`
	FriendID   string    `gorm:"column:friend_id;primaryKey" json:"friend_id"`
	Comment    string    `gorm:"column:comment" json:"comment"`
	FriendFlag int32     `gorm:"column:friend_flag;not null" json:"friend_flag"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
