// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroup = "group"

// Group mapped from table <group>
type Group struct {
	GroupID      string    `gorm:"column:group_id;primaryKey" json:"group_id"`
	Name         string    `gorm:"column:name" json:"name"`
	Introduction string    `gorm:"column:introduction" json:"introduction"`
	Notification string    `gorm:"column:notification" json:"notification"`
	FaceURL      string    `gorm:"column:face_url" json:"face_url"`
	CreateTime   time.Time `gorm:"column:create_time" json:"create_time"`
	Ex           string    `gorm:"column:ex" json:"ex"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
