// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroupMember = "group_member"

// GroupMember mapped from table <group_member>
type GroupMember struct {
	GroupID            string    `gorm:"column:group_id;primaryKey" json:"group_id"`
	UID                string    `gorm:"column:uid;primaryKey" json:"uid"`
	Nickname           string    `gorm:"column:nickname" json:"nickname"`
	UserGroupFaceURL   string    `gorm:"column:user_group_face_url" json:"user_group_face_url"`
	AdministratorLevel int32     `gorm:"column:administrator_level;not null" json:"administrator_level"`
	JoinTime           time.Time `gorm:"column:join_time;not null" json:"join_time"`
}

// TableName GroupMember's table name
func (*GroupMember) TableName() string {
	return TableNameGroupMember
}
